server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fastapi-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: fastapi-app
          service: fastapi-observability-demo
          __path__: /var/log/app/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            service: service
            message: message
      - labels:
          service:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339
